# Generated by Django 4.0 on 2022-01-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname_text', models.CharField(max_length=200)),
                ('lastname_text', models.CharField(max_length=200)),
                ('address_text', models.CharField(max_length=200)),
                ('phone_text', models.CharField(max_length=200)),
            ],
        ),
    ]
