# Generated by Django 4.0 on 2022-01-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fistname_text',
            new_name='firstname_text',
        ),
    ]
