# Generated by Django 4.0 on 2022-02-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptxlist', '0002_pptx_pptx_file_pptx_pptx_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pptx',
            name='pptx_thumbnail',
            field=models.BinaryField(blank=True),
        ),
    ]
