# Generated by Django 4.0 on 2022-02-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptxlist', '0003_pptx_pptx_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptx',
            name='pptx_thumbnail',
            field=models.ImageField(upload_to='images'),
        ),
    ]
