# Generated by Django 4.0 on 2022-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptxlist', '0004_alter_pptx_pptx_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptx',
            name='pptx_thumbnail',
            field=models.ImageField(upload_to='images/% Y/% m/% d/'),
        ),
    ]
